### ISSUE TITLE
Host this react app on surge

### ISSUE THREAD

**Issue by hkedia321** [hkedia321/react-make-notes#1]
Please build this app locally and host it on surge.

**Comment by iamsuganthi** [comment]
What is the surge account that you want to use?

**Comment by hkedia321** [comment]
@enthudrives You can host it using your account. Please choose a suitable sub-domain name.

**Comment by iamsuganthi** [comment]
There you go: http://stickies.surge.sh/

**Comment by hkedia321** [comment]
Thanks @enthudrives! I have updated the project link. It would be great if you can follow up on other issues as well, and help improve this project!
Cheers!
